name: Run Tests & TypeDoc Check

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: v1.2.1
    - name: Install NPM Dependencies
      run: |
        npm install
    - name: Build
      run: |
        npm run build
    - name: Start Anvil with State File
      run: |
        anvil -p 8545 --load-state tests/diamondDeployedAnvilState.json &
        sleep 3
    - name: Run Tests
      run: npm run test
    - name: Run Typedoc Check
      run: npx typedoc --options typedoc.json
