name: Run Tests & TypeDoc Check

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.2.1
      - uses: Forte-Service-Company-Ltd/infrastructure-tooling/.github/actions/typescript-build@v0.0.6
        with:
          node-version: ${{ matrix['node-version'] }}
          package-manager: npm
      ############.   REENABLE AFTER TESTING DOCS!   #########
      # - name: Start Anvil with State File
      #   run: |
      #     anvil -p 8545 --load-state tests/diamondDeployedAnvilState.json &
      #     sleep 3
      # # Runs `npm run test`
      # - uses: Forte-Service-Company-Ltd/infrastructure-tooling/.github/actions/typescript-test@v0.0.6
      #   with:
      #     package-manager: npm
      - uses: Forte-Service-Company-Ltd/infrastructure-tooling/.github/actions/typescript-docs@INF-150-Composite-GitHub-Actions-for-TypeScript--typescript-docs
